version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - dotnet publish DesignacoesReuniao.Web/DesignacoesReuniao.Web.csproj -c Release -o ./publish
      - echo "Arquivos na pasta publish:"
      - ls -la ./publish
artifacts:
  files:
    - '**/*' # Coleta arquivos no diretório base
  base-directory: publish
