version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - dotnet publish DesignacoesReuniao.Web/DesignacoesReuniao.Web.csproj -c Release -o ./publish
      - ls ./publish
      - rm -rf ./DesignacoesReuniao.Web # Remove o diretório conflitante
      - cp -r ./publish/* .
artifacts:
  files:
    - '**/*'
